### PR TITLE
get user email fix

### PR DESCRIPTION
**Pull request by spereverziev**
This would fix getting a user email

### CODE REVIEW

**Comment by vkolodrevskiy** [comment]
This does not fix it!
What if you restart your application? Where this email will be stored?

**Comment by vkolodrevskiy** [comment]
Read http://docs.spring.io/spring-social/docs/1.0.x/reference/html/serviceprovider.html JDBC-based persistence. We need to store email as we do it with accessToken.

**Comment by StasPereverziev** [comment]
Why should we store an email ?

This give us an opportunity to fetch an email with user profile ( not it's returned null )

**Comment by vkolodrevskiy** [comment]
We need to store it to be consistent with the rest of the data that we retrieve while logging in.

How do you want to describe behaviour of getEmail method? 
- "Well guys, you know, sometime this method returns user email, but if you restart your application it will not." :)

**Comment by RomanSyroeshko** [comment]
Thanks, @spereverziev. It works even after application restart.

**Comment by donbeave** [comment]
Hello, guys!

Any way to get merged this commit to main repository?
https://github.com/RomanSyroeshko/spring-social-vkontakte/commit/2cba070094169ec35a985ac0327b6a1cc813d1d3

**Comment by bozzz91** [comment]
yeah it works good, thx
to get changes just fork repo and apply this fix

**Comment by UVSimulation** [comment]
This fix is really necessary. Could you merge it to master, please, or implement another solution.

**Comment by vkolodrevskiy** [comment]
Fixed with latest version, see https://github.com/vkolodrevskiy/spring-social-vkontakte/issues/19

**Pull request closed without merging**
